name: Build MockServer CLI

on: workflow_dispatch

  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.4.x]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8.6.3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm i
    - name: build aplication
      run: npx tsc
    - run: |
        git status --ignored
        git config user.name mock-server-api-bot
        git add -f dist
        git commit -am "[mock-server-api-bot] create dist filder"
        git push origin main
        

    
